//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPLServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx", ConfigurationName="PPLServiceReference.KtmSoap")]
    public interface KtmSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetAccessPointDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel> GetAccessPointDetailAsync(int accessPointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetAccessPointList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel[]> GetAccessPointListAsync(string countryCode, bool allowInactive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetAccessPointDetailByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel> GetAccessPointDetailByCodeAsync(string countryCode, string externalNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetListDeliveryDates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetListDeliveryDatesAsync(string packNumber, string recZipCode, string recStreet, string recCity, bool eveningDelivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetKTMDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.KTMDetail> GetKTMDetailAsync(string customerID, string customerDepID, string KTMID, string couCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetKtmDetailByPackNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.KTMDetail> GetKtmDetailByPackNumberAsync(string packNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetKTMList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.KTMDetail[]> GetKTMListAsync(string couCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://StorageClub/AccessPoint/ASMX/Ktm.asmx/GetAllKTMList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PPLServiceReference.KTMDetail[]> GetAllKTMListAsync(string couCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx")]
    public partial class AccessPointDetailModel
    {
        
        private int idField;
        
        private string codeField;
        
        private string depotField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string countryField;
        
        private string zipCodeField;
        
        private string parcelshopNameField;
        
        private string phoneField;
        
        private string wwwField;
        
        private string ktmNoteField;
        
        private CoordinatesModel gpsField;
        
        private string[] openHoursField;
        
        private ExternalNumberModel[] externalNumbersField;
        
        private bool visiblePsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Depot
        {
            get
            {
                return this.depotField;
            }
            set
            {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ParcelshopName
        {
            get
            {
                return this.parcelshopNameField;
            }
            set
            {
                this.parcelshopNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Www
        {
            get
            {
                return this.wwwField;
            }
            set
            {
                this.wwwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string KtmNote
        {
            get
            {
                return this.ktmNoteField;
            }
            set
            {
                this.ktmNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public CoordinatesModel Gps
        {
            get
            {
                return this.gpsField;
            }
            set
            {
                this.gpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public string[] OpenHours
        {
            get
            {
                return this.openHoursField;
            }
            set
            {
                this.openHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public ExternalNumberModel[] ExternalNumbers
        {
            get
            {
                return this.externalNumbersField;
            }
            set
            {
                this.externalNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool VisiblePs
        {
            get
            {
                return this.visiblePsField;
            }
            set
            {
                this.visiblePsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx")]
    public partial class CoordinatesModel
    {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx")]
    public partial class KTMDetail
    {
        
        private string gpsNField;
        
        private string gpsEField;
        
        private string positionField;
        
        private string openTimeField;
        
        private string qrCodeField;
        
        private string customerName1Field;
        
        private string customerName2Field;
        
        private string kTMIDField;
        
        private string countryIdField;
        
        private string cityField;
        
        private string street1Field;
        
        private string zipCodeField;
        
        private string customerIdField;
        
        private string customerDepIdField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string gpsN
        {
            get
            {
                return this.gpsNField;
            }
            set
            {
                this.gpsNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string gpsE
        {
            get
            {
                return this.gpsEField;
            }
            set
            {
                this.gpsEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string openTime
        {
            get
            {
                return this.openTimeField;
            }
            set
            {
                this.openTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string qrCode
        {
            get
            {
                return this.qrCodeField;
            }
            set
            {
                this.qrCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string customerName1
        {
            get
            {
                return this.customerName1Field;
            }
            set
            {
                this.customerName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string customerName2
        {
            get
            {
                return this.customerName2Field;
            }
            set
            {
                this.customerName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string KTMID
        {
            get
            {
                return this.kTMIDField;
            }
            set
            {
                this.kTMIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string street1
        {
            get
            {
                return this.street1Field;
            }
            set
            {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string customerDepId
        {
            get
            {
                return this.customerDepIdField;
            }
            set
            {
                this.customerDepIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx")]
    public partial class ExternalNumberModel
    {
        
        private ConstCustExtNumType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConstCustExtNumType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://StorageClub/AccessPoint/ASMX/Ktm.asmx")]
    public enum ConstCustExtNumType
    {
        
        /// <remarks/>
        Esyco1,
        
        /// <remarks/>
        Sap2,
        
        /// <remarks/>
        Ktm3,
        
        /// <remarks/>
        Eps14,
        
        /// <remarks/>
        Objednavka5,
        
        /// <remarks/>
        InHouse6,
        
        /// <remarks/>
        KtmPartnerskeCislo7,
        
        /// <remarks/>
        Tp8,
        
        /// <remarks/>
        KtmPartnerskeId9,
        
        /// <remarks/>
        EsycoSubjekt10,
        
        /// <remarks/>
        KtmDhl11,
        
        /// <remarks/>
        DhlpsId12,
        
        /// <remarks/>
        CpsPsId13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KtmSoapChannel : PPLServiceReference.KtmSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KtmSoapClient : System.ServiceModel.ClientBase<PPLServiceReference.KtmSoap>, PPLServiceReference.KtmSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KtmSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KtmSoapClient.GetBindingForEndpoint(endpointConfiguration), KtmSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KtmSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KtmSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KtmSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KtmSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KtmSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel> GetAccessPointDetailAsync(int accessPointId)
        {
            return base.Channel.GetAccessPointDetailAsync(accessPointId);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel[]> GetAccessPointListAsync(string countryCode, bool allowInactive)
        {
            return base.Channel.GetAccessPointListAsync(countryCode, allowInactive);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.AccessPointDetailModel> GetAccessPointDetailByCodeAsync(string countryCode, string externalNumber)
        {
            return base.Channel.GetAccessPointDetailByCodeAsync(countryCode, externalNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> GetListDeliveryDatesAsync(string packNumber, string recZipCode, string recStreet, string recCity, bool eveningDelivery)
        {
            return base.Channel.GetListDeliveryDatesAsync(packNumber, recZipCode, recStreet, recCity, eveningDelivery);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.KTMDetail> GetKTMDetailAsync(string customerID, string customerDepID, string KTMID, string couCode)
        {
            return base.Channel.GetKTMDetailAsync(customerID, customerDepID, KTMID, couCode);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.KTMDetail> GetKtmDetailByPackNumberAsync(string packNumber)
        {
            return base.Channel.GetKtmDetailByPackNumberAsync(packNumber);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.KTMDetail[]> GetKTMListAsync(string couCode)
        {
            return base.Channel.GetKTMListAsync(couCode);
        }
        
        public System.Threading.Tasks.Task<PPLServiceReference.KTMDetail[]> GetAllKTMListAsync(string couCode)
        {
            return base.Channel.GetAllKTMListAsync(couCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KtmSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.KtmSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KtmSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.pplbalik.cz/ASM/Ktm.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.KtmSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.pplbalik.cz/ASM/Ktm.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            KtmSoap,
            
            KtmSoap12,
        }
    }
}
